default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  # Prefer DATABASE_URL if present (Heroku/Docker/etc). Otherwise build from parts.
  url: <%= ENV["DATABASE_URL"] %>
  host: <%= ENV.fetch("POSTGRESQL_ADDRESS", "localhost") %>
  port: <%= ENV.fetch("POSTGRESQL_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRESQL_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRESQL_PASSWORD", "postgres") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRESQL_DB", "geolocation_dev") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRESQL_TEST_DB", "geolocation_test") %>
  pool: 10

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRESQL_PROD_DB", "geolocation_prod") %>
